import MainProvider from '@/components/MainProvider'
import './globals.css'
import type { Metadata } from 'next'
import { Lexend } from 'next/font/google'

const lexend = Lexend({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Unite',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${lexend.className} bg-background`}>
        <MainProvider>{children}</MainProvider>
      </body>
    </html>
  )
}
